### ISSUE TITLE
Unexpected type string in list

### ISSUE THREAD

**Issue by jrowinski88** [terraform-aws-modules/terraform-aws-elb#12]
Hi there,

First off I want to thank you for creating this great module! 

I just wanted to reach out if you have come across any issues regarding the outputs? I specify a list of instances for the ELB, but terraform seems to complain about the output of instances.

This is the error I get:

```
* module.us-west-1-ELB.module.elb.output.this_elb_instances: concat: unexpected type string in list of type list in:

${element(concat(aws_elb.this.*.instances, list("")), 0)}
```

Thanks for your help!

**Comment by antonbabenko** [comment]
Glad that you like it, make sure you are using latest version v1.3.1, where this issue has been fixed - https://github.com/terraform-aws-modules/terraform-aws-elb/issues/10

**Comment by jrowinski88** [comment]
Hey Anton,

Thanks for getting back so fast, I am using the lastest version so not sure why I am receiving this error. I just have 2 instance id's defined in my module definition. I tried pulling your latest version and still seeing this error.

**Comment by antonbabenko** [comment]
Strange, I will have to look into it on Monday or you can try to investigate yourself and send a PR. Whatever is easier for you.

**Comment by MorningTho** [comment]
Hey, 

Same here, updated to 1.4.0 and I have this output : 

```* module.dWARfAPIDev_elb.module.elb.output.this_elb_instances: concat: unexpected type string in list of type list in:
${element(concat(aws_elb.this.*.instances, list("")), 0)}```

And here's the code related to this output :

```module "dWARfAPIDev_elb" {
  source = "terraform-aws-modules/elb/aws"
  version = "1.4.0"

  name = "dwarf-api-preprod-lb"

  subnets         = ["${aws_subnet.dWARfAPI_preprod.id}"]
  security_groups = ["${module.APIs_preproduction_LB_SG.this_security_group_id}"]
  internal        = false

  listener = [
    {
      instance_port      = "8085"
      instance_protocol  = "HTTP"
      lb_port            = "443"
      lb_protocol        = "HTTPS"
    },
  ]

  health_check = [
    {
      target                        = "HTTP:80/"
      interval                      = 30
      healthy_threshold    = 2
      unhealthy_threshold = 2
      timeout             = 5
    },
  ]

  tags = {
    Terraform   = "true"
    Environment = "dev"
  }
}```

**Comment by antonbabenko** [comment]
[v1.4.1](https://github.com/terraform-aws-modules/terraform-aws-elb/releases/v1.4.1) is released. I have tested it by running examples and it should work for your cases too.

**Comment by jrowinski88** [comment]
Thanks @antonbabenko !

Sorry for not following up earlier, had a long weekend out here :)
